### ISSUE TITLE
Vuex can't work??

### ISSUE THREAD

**Issue by lzq920** [joeldenning/coexisting-vue-microfrontends#14]
```
app-errors.js:9 Uncaught main: Application 'main' died in status LOADING_SOURCE_CODE: t.isBuffer is not a function
    at y (<anonymous>:1:2232)
    at f (<anonymous>:1:3275)
    at Object.<anonymous> (<anonymous>:1:928)
    at Object.r (<anonymous>:1:375)
    at Object.emit (<anonymous>:1:694)
    at devtoolPlugin (http://localhost:8080/app.js:12740:15)
    at new Store (http://localhost:8080/app.js:13042:5)
    at Module../src/store.js (http://localhost:8080/app.js:15034:64)
    at __webpack_require__ (http://localhost:8080/app.js:737:30)
    at fn (http://localhost:8080/app.js:111:20)
```
```
import "./set-public-path";
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import singleSpaVue from "single-spa-vue";
import store from "./store";
Vue.config.productionTip = false;

const vueLifecycles = singleSpaVue({
    Vue,
    appOptions: {
        render: h => h(App),
        router,
        store
    }
});

export const bootstrap = vueLifecycles.bootstrap;
export const mount = vueLifecycles.mount;
export const unmount = vueLifecycles.unmount;

```

**Comment by joeldenning** [comment]
single-spa and Vuex can work together.

Perhaps your issue is related to one of the following issues?

- https://github.com/vuejs/vue-devtools/issues/874
- https://github.com/vuejs/vue-devtools/issues/910

**Comment by lzq920** [comment]
thank you，updated vue-devtools v5.1.1  solve the problem

**Comment by Jainith** [comment]
> thank you，updated vue-devtools v5.1.1 solve the problem

Still this issue isn't fixed to me. Pls provide me code
