### ISSUE TITLE
Application died in status LOADING_SOURCE_CODE: window.Vue.use is not a function

### ISSUE THREAD

**Issue by linchanglin** [joeldenning/coexisting-vue-microfrontends#25]
singleSpa.registerApplication(
         'proj1',
            () => System.import('proj1'),
            location => location.hash.startsWith('#/jpro')
            // location => true
          )

when I use:  location => location.hash.startsWith('#/jpro')  , I get the error below，but it works fine  when I use:  location => true; I don't konw why? please help me. thanks a lot 

Uncaught proj1: Application 'proj1' died in status LOADING_SOURCE_CODE: window.Vue.use is not a function
    at Module../node_modules/vue-router/dist/vue-router.esm.js (http://localhost:8002/app.js:261976:14)
    at __webpack_require__ (http://localhost:8002/app.js:778:30)
    at fn (http://localhost:8002/app.js:141:20)
    at Module../src/router/index.js (http://localhost:8002/app.js:283598:68)
    at __webpack_require__ (http://localhost:8002/app.js:778:30)
    at fn (http://localhost:8002/app.js:141:20)
    at Module../src/main.js (http://localhost:8002/app.js:281169:67)
    at __webpack_require__ (http://localhost:8002/app.js:778:30)
    at fn (http://localhost:8002/app.js:141:20)
    at Object.2 (http://localhost:8002/app.js:284653:18)

**Comment by linchanglin** [comment]
this my framework mistake 。。sorry

**Comment by linchanglin** [comment]
this my framework mistake 。。sorry
